# Generated by Django 4.2.30 on 2026-07-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('final_score', models.FloatField(default=0)),
                ('decision', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0)),
                ('semantic_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_result', models.JSONField(default=dict)),
            ],
        ),
    ]
