"""
TEMPORARY, ISOLATED diagnostic script -- not a management command, not part
of the application, not imported anywhere else. Deletes nothing, patches
nothing permanently: it monkey-patches `requests.post` only inside this
process, for the duration of this script, purely to observe (never alter)
the real HTTP call/response between the REAL, unmodified
analyze_job_description() -> generate_json() code path and Ollama.

Captures, for both the known-SUCCESS text and the known-FAILURE
(job_b.description) text, using the exact same application code path:

  1. exact job_description bytes
  2. exact final prompt generated by analyze_job_description()
  3. len(prompt)
  4. repr(prompt) hash (sha256, so it's short and diffable)
  5. exact payload sent to Ollama
  6. HTTP status
  7. full raw HTTP response body
  8. data["response"]
  9. repr(data["response"])
  10. result before json.loads()
  11. exception if json.loads() fails

Then runs the FAILURE text 5x to test determinism (Step 4).

Then runs process_job(job_b) once through the real, unmodified function
(Step 7 Test C prerequisite -- just observing here, not asserting pass/fail
yet; that's for the regression-test step after a fix is identified).

Usage (from the Django project root, venv active):

    python ai_engine/diagnose_job_parser_bug.py

Nothing here is left running or patched after the script exits -- the
monkey-patch is local to this process only, never written to disk, and no
application file is imported-and-modified. Safe to delete this file at any
time; it is not referenced by any other module.
"""

import hashlib
import json
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings")

import django
django.setup()

import requests as _requests_module

# ---------------------------------------------------------------------
# Monkey-patch requests.post ONLY inside ai_engine.services.llm_service's
# already-imported `requests` reference, for THIS PROCESS ONLY. We call
# the REAL requests.post underneath and only observe start/end + payload
# + response -- never modify, never fake a value.
# ---------------------------------------------------------------------
from ai_engine.services import llm_service as _llm_service_module

_REAL_POST = _requests_module.post
_CAPTURED_CALLS = []


def _spy_post(url, json=None, timeout=None, **kwargs):
    entry = {
        "url": url,
        "payload": json,
        "timeout": timeout,
    }
    try:
        response = _REAL_POST(url, json=json, timeout=timeout, **kwargs)
        entry["http_status"] = response.status_code
        entry["raw_text"] = response.text
        try:
            entry["response_json"] = response.json()
        except Exception as parse_err:
            entry["response_json"] = None
            entry["response_json_parse_error"] = repr(parse_err)
        entry["exception"] = None
        _CAPTURED_CALLS.append(entry)
        return response
    except Exception as e:
        entry["http_status"] = None
        entry["raw_text"] = None
        entry["response_json"] = None
        entry["exception"] = repr(e)
        _CAPTURED_CALLS.append(entry)
        raise


_llm_service_module.requests.post = _spy_post

# ---------------------------------------------------------------------
# Also capture the exact final prompt string analyze_job_description()
# builds, WITHOUT changing its behavior: we wrap generate_json (the
# function analyze_job_description calls) to record `prompt` before
# passing through to the real implementation unchanged.
# ---------------------------------------------------------------------
from ai_engine.services import llm_job_parser as _llm_job_parser_module

_REAL_GENERATE_JSON = _llm_job_parser_module.generate_json
_CAPTURED_PROMPTS = []


def _spy_generate_json(prompt, default=None):
    _CAPTURED_PROMPTS.append(prompt)
    return _REAL_GENERATE_JSON(prompt=prompt, default=default)


_llm_job_parser_module.generate_json = _spy_generate_json

# NOW import the real, unmodified function under test (after patching its
# module-level references above).
from ai_engine.services.llm_job_parser import analyze_job_description


def _sha256(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def _dump_call(label, call, prompt):
    print(f"\n----- {label}: captured HTTP call -----")
    print(f"len(prompt)        : {len(prompt)}")
    print(f"prompt sha256[:16]  : {_sha256(prompt)}")
    print(f"repr(prompt)[:300]  : {repr(prompt)[:300]}...")
    if call is None:
        print("!! NO requests.post call was captured for this run !!")
        return
    print(f"payload.model       : {call['payload'].get('model') if call['payload'] else None}")
    print(f"payload.format      : {call['payload'].get('format') if call['payload'] else None}")
    print(f"payload.stream      : {call['payload'].get('stream') if call['payload'] else None}")
    print(f"payload prompt len  : {len(call['payload'].get('prompt', '')) if call['payload'] else None}")
    print(f"http_status         : {call['http_status']}")
    print(f"exception           : {call['exception']}")
    if call.get("response_json") is not None:
        raw_response_field = call["response_json"].get("response", "")
        print(f"data['response']    : {raw_response_field!r}")
        print(f"len(data['response']): {len(raw_response_field)}")
        try:
            parsed = json.loads(raw_response_field) if raw_response_field else None
            print(f"json.loads(data['response']) -> {parsed!r}")
        except Exception as e:
            print(f"json.loads(data['response']) RAISED: {e!r}")
        # Other Ollama fields that can reveal truncation/early-stop
        for k in ("done", "done_reason", "total_duration", "eval_count", "prompt_eval_count"):
            if k in call["response_json"]:
                print(f"data['{k}']".ljust(22) + f": {call['response_json'][k]!r}")
    else:
        print(f"raw_text[:500]      : {(call.get('raw_text') or '')[:500]!r}")


def run_case(label, description_text):
    _CAPTURED_CALLS.clear()
    _CAPTURED_PROMPTS.clear()

    print(f"\n{'='*70}\n{label}\n{'='*70}")
    print(f"description bytes  : {description_text.encode('utf-8')!r}")
    print(f"len(description)   : {len(description_text)}")

    result = analyze_job_description(description_text)

    print(f"\nFINAL RESULT analyze_job_description() -> {result!r}")

    prompt = _CAPTURED_PROMPTS[0] if _CAPTURED_PROMPTS else "<no prompt captured>"
    call = _CAPTURED_CALLS[0] if _CAPTURED_CALLS else None
    _dump_call(label, call, prompt)

    return result, prompt, call


# =====================================================================
# STEP 2 -- SUCCESS vs FAILURE, exact same code path
# =====================================================================

SUCCESS_TEXT = """
The ICT Officer supports the Ministry's information systems,
manages database infrastructure, and provides technical support
to civil service staff. Requires a Bachelor's degree in Information
Technology and at least 2 years of relevant experience.
"""

try:
    from talent.models import Job
    job_b = Job.objects.get(title="BENCHMARK - ICT Officer (isolated)")
    FAILURE_TEXT = job_b.description
    HAVE_JOB_B = True
except Exception as e:
    print(f"!! Could not load job_b from DB: {e!r} -- FAILURE case will use a literal copy instead.")
    FAILURE_TEXT = (
        "The ICT Officer supports the Ministry's information systems, "
        "manages database infrastructure, and provides technical support "
        "to civil service staff. Requires a Bachelor's degree in "
        "Information Technology and at least 2 years of relevant experience."
    )
    HAVE_JOB_B = False
    job_b = None

result_success, prompt_success, call_success = run_case("CASE: SUCCESS TEXT (manual multiline)", SUCCESS_TEXT)
result_failure, prompt_failure, call_failure = run_case("CASE: FAILURE TEXT (job_b.description from DB)", FAILURE_TEXT)

print(f"\n{'='*70}\nSTEP 2 -- DIRECT COMPARISON\n{'='*70}")
print(f"len(prompt) success vs failure : {len(prompt_success)} vs {len(prompt_failure)}")
print(f"prompt sha256 success           : {_sha256(prompt_success)}")
print(f"prompt sha256 failure           : {_sha256(prompt_failure)}")
print(f"prompts byte-identical except description text? "
      f"{prompt_success.replace(SUCCESS_TEXT, '') == prompt_failure.replace(FAILURE_TEXT, '')}")

# =====================================================================
# STEP 4 -- determinism test, 5x on the FAILURE text, exact same path
# =====================================================================

print(f"\n{'='*70}\nSTEP 4 -- DETERMINISM: FAILURE TEXT x5\n{'='*70}")
determinism_results = []
for i in range(5):
    _CAPTURED_CALLS.clear()
    _CAPTURED_PROMPTS.clear()
    r = analyze_job_description(FAILURE_TEXT)
    call = _CAPTURED_CALLS[0] if _CAPTURED_CALLS else None
    raw_field = None
    if call and call.get("response_json"):
        raw_field = call["response_json"].get("response", "")
    determinism_results.append((r, raw_field))
    print(f"  Run {i+1}: result={r!r}  raw_response_field={raw_field!r}")

all_empty = all(r == {} for r, _ in determinism_results)
any_empty = any(r == {} for r, _ in determinism_results)
print(f"\nAll 5 runs empty ({{}})   : {all_empty}")
print(f"Any run empty ({{}})      : {any_empty}")
print(f"Mixed results (nondeterministic): {any_empty and not all_empty}")

# =====================================================================
# Also run the SUCCESS text as a single-line string (same content,
# no leading/trailing newline or indentation) -- isolates "multi-line
# triple-quoted Python literal" vs "single-line runtime string" as a
# variable, independent of DB vs non-DB origin.
# =====================================================================

SUCCESS_TEXT_SINGLE_LINE = " ".join(SUCCESS_TEXT.split())
print(f"\n{'='*70}\nEXTRA: SUCCESS TEXT collapsed to single line (no DB involved)\n{'='*70}")
result_single, prompt_single, call_single = run_case(
    "CASE: SUCCESS TEXT, single-line (no DB)", SUCCESS_TEXT_SINGLE_LINE
)

# =====================================================================
# process_job(job_b) -- real, unmodified function, one observed run
# =====================================================================

if HAVE_JOB_B:
    print(f"\n{'='*70}\nprocess_job(job_b) -- real function, one observed run\n{'='*70}")
    from ai_engine.services.job_pipeline import process_job
    try:
        job_b.ai_processed = False
        job_b.save(update_fields=["ai_processed"])
        result_job = process_job(job_b)
        print(f"process_job() SUCCEEDED: ai_processed={result_job.ai_processed}, "
              f"ai_job_profile={result_job.ai_job_profile!r}")
    except Exception as e:
        print(f"process_job() RAISED: {e!r}")
else:
    print("\nSkipping process_job(job_b) -- job_b not found in DB in this environment.")

print(f"\n{'='*70}\nDONE -- restoring original requests.post / generate_json\n{'='*70}")
_llm_service_module.requests.post = _REAL_POST
_llm_job_parser_module.generate_json = _REAL_GENERATE_JSON