# Generated by Django 4.2.30 on 2026-10-02 06:45

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.CaseInsensitiveUserManager()),
            ],
        ),
    ]
