"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = 'accounts.User'


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-8rnu)29ui6-hqah8lyb69geeurg&&2tf9j0%%@3%kmz*g!12gb"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'

# TASK H (2026-10-03): CSC pilot/demo labeling only -- purely
# presentational (see accounts/context_processors.py + templates/
# base.html). Does NOT change any AI pipeline, scoring, RAG, OCR,
# auth, or database behavior. Default False, so production (Railway)
# renders byte-identical to before unless this env var is explicitly
# set for a pilot session. When True, every page shows a banner
# clarifying the AI output is decision support, not a final
# recruitment decision, and that the session is a research/pilot
# demonstration -- required positioning for the CSC pilot per Task H.
PILOT_MODE = os.environ.get("PILOT_MODE", "False") == "True"


SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1200  # 20 minutes
SESSION_SAVE_EVERY_REQUEST = True  # idle clock resets on activity


ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

# SITE_URL -- the public address of this site, used ONLY to build links
# inside emails that are sent from the background worker (which has no
# web request to read the host from), e.g. the "view your AI
# recommendation" link. Set SITE_URL explicitly in production
# (e.g. https://your-app.up.railway.app). If it is not set, Railway's
# own RAILWAY_PUBLIC_DOMAIN variable is used when present, and
# otherwise the local development address.
_railway_domain = os.environ.get("RAILWAY_PUBLIC_DOMAIN", "").strip()

SITE_URL = (
    os.environ.get("SITE_URL", "").strip()
    or (f"https://{_railway_domain}" if _railway_domain else "")
    or "http://127.0.0.1:8000"
).rstrip("/")

# CSRF_TRUSTED_ORIGINS -- only needed for a public HTTPS deployment
# (e.g. Render). Empty by default so local dev / LAN demos (plain
# HTTP, same-origin requests) are unaffected -- Django only requires
# this list to contain something when it's non-empty.
_csrf_trusted_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "").strip()

CSRF_TRUSTED_ORIGINS = (
    [origin.strip() for origin in _csrf_trusted_origins.split(",") if origin.strip()]
    if _csrf_trusted_origins
    else []
)

# Render (and most PaaS hosts) terminate HTTPS at a proxy and forward
# plain HTTP internally to gunicorn. Without this, Django would think
# every request is insecure (request.is_secure() == False) even
# though the browser is genuinely talking HTTPS, which breaks CSRF
# origin checks. Safe to leave in place for local dev too -- it only
# takes effect when the proxy header is actually present.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 'recruitment',
    'talent',
    'ai_engine',
    'accounts',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
        },
    }
}

import dj_database_url

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if DATABASE_URL:
    DATABASES['default'] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600
    )


from django.db.backends.signals import connection_created


def _enable_sqlite_wal_mode(sender, connection, **kwargs):

    if connection.vendor == "sqlite":

        with connection.cursor() as cursor:
            cursor.execute("PRAGMA journal_mode=WAL;")


connection_created.connect(_enable_sqlite_wal_mode)


# Password policy is intentionally lenient so candidates (many of whom
# are not used to strict rules) can register easily. Only a short
# minimum length is enforced. No "too common", "all numeric" or
# "similar to username" checks.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 6},
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Reject request bodies over ~6MB before Django even finishes
# parsing the upload (defense-in-depth on top of the 5MB CV size
# check in talent/views.py — this stops an oversized upload from
# being buffered into memory at all).
DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024

GEMINI_MODEL = os.environ.get(
    "GEMINI_MODEL",
    "gemini-2.5-flash"
)

GEMINI_API_KEY = os.environ.get(
    "GEMINI_API_KEY",
    ""
)

LLM_PROVIDER="local"

# TASK K (2026-10-07): how long a password-reset link stays valid, in
# seconds. Django's own default is 3 days; 1 hour is safer for a
# platform that holds candidate data. Override with the
# PASSWORD_RESET_TIMEOUT environment variable if needed.
PASSWORD_RESET_TIMEOUT = int(
    os.environ.get("PASSWORD_RESET_TIMEOUT", "3600")
)

# =====================================================
# EMAIL (registration / email verification feature)
# =====================================================
# Defaults to Django's console backend -- verification emails print
# to the runserver terminal instead of actually sending, which is a
# safe, zero-setup default for local development. Set EMAIL_BACKEND
# in .env to switch to real SMTP delivery; nothing below is
# hardcoded, all of it comes from environment variables so no
# credential ever needs to be committed.

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
)

EMAIL_HOST = os.environ.get("EMAIL_HOST", "")

EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))

EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")

EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "no-reply@ai-recruitment.local"
)

# Brevo HTTPS API email backend (accounts/email_backends.py). Only
# used if EMAIL_BACKEND is set to
# "accounts.email_backends.BrevoAPIEmailBackend" -- for local
# development / SMTP-capable hosts, EMAIL_BACKEND stays as the
# console/SMTP backend above and this key is simply unused.
BREVO_API_KEY = os.environ.get("BREVO_API_KEY", "")
STATIC_ROOT = BASE_DIR / "staticfiles"