"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = 'accounts.User'


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-8rnu)29ui6-hqah8lyb69geeurg&&2tf9j0%%@3%kmz*g!12gb"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

# CSRF_TRUSTED_ORIGINS -- only needed for a public HTTPS deployment
# (e.g. Render). Empty by default so local dev / LAN demos (plain
# HTTP, same-origin requests) are unaffected -- Django only requires
# this list to contain something when it's non-empty.
_csrf_trusted_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "").strip()

CSRF_TRUSTED_ORIGINS = (
    [origin.strip() for origin in _csrf_trusted_origins.split(",") if origin.strip()]
    if _csrf_trusted_origins
    else []
)

# Render (and most PaaS hosts) terminate HTTPS at a proxy and forward
# plain HTTP internally to gunicorn. Without this, Django would think
# every request is insecure (request.is_secure() == False) even
# though the browser is genuinely talking HTTPS, which breaks CSRF
# origin checks. Safe to leave in place for local dev too -- it only
# takes effect when the proxy header is actually present.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 'recruitment',
    'talent',
    'ai_engine',
    'accounts',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# username admin password: admin
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ai_recruitment',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': '127.0.0.1',
#         'PORT': '3309',  # sesuaikan dengan XAMPP kamu
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Reject request bodies over ~6MB before Django even finishes
# parsing the upload (defense-in-depth on top of the 5MB CV size
# check in talent/views.py — this stops an oversized upload from
# being buffered into memory at all).
DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024

GEMINI_MODEL = os.environ.get(
    "GEMINI_MODEL",
    "gemini-2.5-flash"
)

GEMINI_API_KEY = os.environ.get(
    "GEMINI_API_KEY",
    ""
)

LLM_PROVIDER="local"

# =====================================================
# EMAIL (registration / email verification feature)
# =====================================================
# Defaults to Django's console backend -- verification emails print
# to the runserver terminal instead of actually sending, which is a
# safe, zero-setup default for local development. Set EMAIL_BACKEND
# in .env to switch to real SMTP delivery; nothing below is
# hardcoded, all of it comes from environment variables so no
# credential ever needs to be committed.

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
)

EMAIL_HOST = os.environ.get("EMAIL_HOST", "")

EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))

EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")

EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "no-reply@ai-recruitment.local"
)

EMAIL_TIMEOUT = 10