# Generated by Django 4.2.30 on 2026-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
