# Generated by Django 4.2.30 on 2026-06-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_candidate_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
