# Generated by Django 4.2.30 on 2026-06-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_candidate_candidate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='professional_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
