# Generated by Django 4.2.30 on 2026-07-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_candidate_certifications_candidate_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_decision',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_explainable_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_job_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_model',
            field=models.CharField(default='gemma3:12b', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_processing_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_rule_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_semantic_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_skill_gap',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_status',
            field=models.CharField(default='SUCCESS', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_version',
            field=models.CharField(default='1.0.0', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='ai_feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
