# Generated by Django 4.2.30 on 2026-07-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_application_ai_confidence_application_ai_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ai_job_profile',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ai_processing_time',
            field=models.FloatField(default=0),
        ),
    ]
