# Generated by Django 6.1.1 on 2026-09-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0006_job_ai_job_profile_job_ai_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_rag_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='ai_rag_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
