# Generated by Django 6.1.1 on 2026-09-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0008_humandecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_provider',
            field=models.CharField(default='Ollama (local)', max_length=50),
        ),
    ]
