# Generated by Django 4.2.30 on 2026-10-06 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0010_candidate_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="extraction_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_bytes", models.BinaryField()),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_document",
                        to="talent.application",
                    ),
                ),
            ],
        ),
    ]